specfile_path: rebase-helper.spec
synced_files:
    - rebase-helper.spec
    - .packit.yml
upstream_package_name: rebase-helper
downstream_package_name: rebase-helper
current_version_command: ["python3", "setup.py", "--version"]
create_tarball_command: ["python3", "setup.py", "sdist", "--base-name", "rebase-helper", "--dist-dir", "."]
jobs:
    - job: copr_build
      trigger: pull_request
      metadata:
          targets:
              - fedora-rawhide-x86_64
              - fedora-31-x86_64
              - fedora-30-x86_64
    - job: propose_downstream
      trigger: release
    - job: propose_downstream
      trigger: release
      metadata:
          dist-git-branch: f31
    - job: propose_downstream
      trigger: release
      metadata:
          dist-git-branch: f30
