jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
        - epel-8-x86_64
  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches:
        - fedora-all
        - epel8
actions:
  create-archive:
  - "python3 setup.py sdist --base-name rebase-helper --dist-dir ."
  - "bash -c 'ls -1t ./rebase-helper-*.tar.gz | head -n 1'"
