current_version_command: ["python3", "setup.py", "--version"]
create_tarball_command: ["python3", "setup.py", "sdist", "--base-name", "rebase-helper", "--dist-dir", "."]
jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
  - job: propose_downstream
    trigger: release
    metadata:
      dist-git-branch: fedora-all
