FROM registry.access.redhat.com/ubi8-minimal:latest

COPY containers/webhooks.py /webhooks.py

RUN microdnf install python3-pip python3-cryptography git && microdnf clean all
RUN pip3 install --no-cache-dir GitPython twine

EXPOSE 80/TCP

CMD ["python3", "-u", "/webhooks.py"]
